#
# https://projecteuler.net/problem=2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
#
#
#
# Terminos pares en la secuencia de fibonachi hasta los 4 millones

max_value = 4000000
fibo_terms = [1, 2]
fibo = 1
counter = 0
plus = 0

while (plus < max_value):
    fibo = fibo_terms[counter] + fibo_terms[counter + 1]
    fibo_terms.append(fibo)
    if(fibo % 2 == 0):
        plus += fibo

    counter += 1

print(plus + 2)
